2024-11-27 13:40:34,631 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/lucian/PycharmProjects/pythonProject2/tests_12_4.py", line 74, in test_run
    r2 = Runner(15)
         ^^^^^^^^^^
  File "/Users/lucian/PycharmProjects/pythonProject2/tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-27 13:40:34,633 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/lucian/PycharmProjects/pythonProject2/tests_12_4.py", line 63, in test_walk
    r1= Runner("Вася", -5)
        ^^^^^^^^^^^^^^^^^^
  File "/Users/lucian/PycharmProjects/pythonProject2/tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
